-- setup database

CREATE TABLE LOCATION (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SHORTNAME VARCHAR(40),
	NAME VARCHAR(40),
	STREET VARCHAR(40),
	ZIP VARCHAR(10),
	STATE VARCHAR (40),
	COUNTRY VARCHAR(40),
	URL VARCHAR(70),
	LONGITUDE VARCHAR(20),
	LONGITUDE VARCHAR(20),
	COMMENT VARCHAR(100),
	CITY VARCHAR(30)
) ENGINE=INNODB;

CREATE TABLE MEASURAND (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CREATIONDATE TIMESTAMP NOT NULL,
	LOCATION_ID INT NOT NULL,
	SENSOR_ID INT NOT NULL,
	VALUE REAL NOT NULL,
	UNIT VARCHAR(3) NOT NULL, 
	FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(ID)
) ENGINE=INNODB;
