-- setup database

PRAGMA foreign_keys = ON;

CREATE TABLE LOCATION (
	ID INTEGER PRIMARY KEY,
	SHORTNAME char(40),
	NAME char(40),
	STREET char(40),
	ZIP char(10),
	STATE char (40),
	COUNTRY char(40),
	URL char(70),
	LONG char(20),
	LAT char(20),
	COMMENT char(100),
	CITY char(30)
);

CREATE TABLE MEASURAND (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CREATIONDATE TIMESTAMP NOT NULL,
	LOCATION_ID INTEGER NOT NULL,
	SENSOR_ID INTEGER NOT NULL,
	VALUE REAL NOT NULL,
	UNIT CHAR(3) NOT NULL, 
	FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION
);

CREATE TABLE SYNC_QUEUE (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	MEASURAND_ID INTEGER NOT NULL,
	FOREIGN KEY(MEASURAND_ID) REFERENCES MEASURAND
);
